// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace testEsp32.Models
{
    public partial class Outputs
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? Board { get; set; }
        public int? Gpio { get; set; }
        public int? State { get; set; }

        public virtual Boards BoardNavigation { get; set; }
    }
}