// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace testEsp32MVC.Models
{
    public partial class Boards
    {
        public Boards()
        {
            Outputs = new HashSet<Outputs>();
        }

        public int Id { get; set; }
        public int Board { get; set; }
        public byte[] LastRequest { get; set; }

        public virtual ICollection<Outputs> Outputs { get; set; }
    }
}